Repository NordicSemiconductor/pc-nrfconnect-programmer, pull requests merged in 2024-02, with the labels that each got.

#440 doc: programmer: bring docs up-to-date
  README.md
  doc/docs/index.md
  doc/docs/installing.md
  doc/docs/overview.md
  doc/docs/programming_dk.md
  doc/docs/programming_dongle.md
  doc/docs/revision_history.md
  doc/docs/screenshots/nRF_Connect_for_Desktop_Prog_about.png
  doc/docs/screenshots/programmer.png
  doc/docs/screenshots/programmer_overview.png
  doc/docs/screenshots/programmer_with_device.png
  doc/docs/troubleshooting.md
  doc/mkdocs.yml
  src/components/ControlPanel.tsx
  src/components/DocumentationSections.tsx
Labels: documentation, doc required

#441 ci: use shared labels workflow
  .github/workflows/labels.yml
Labels: doc not required, ui not required

#443 Feat/nrfutil device
  Changelog.md
  package-lock.json
  package.json
  src/actions/jlinkTargetActions.ts
  src/actions/mcubootTargetActions.ts
  src/actions/modemTargetActions.ts
  src/actions/usbsdfuTargetActions.ts
  src/components/CoreInfoView.tsx
  src/components/DeviceMemoryView.tsx
  src/components/FileMemoryView.tsx
  src/index.tsx
  src/reducers/deviceDefinitionReducer.ts
  src/util/deviceTypes.ts
  src/util/devices.ts
  src/util/regions.ts
Labels: doc not required, ui not required

#445 Fix: round jlink progress logging reporting
  src/actions/jlinkTargetActions.ts
Labels: doc not required, ui not required

#446 Feat/disable mcu toggle
  Changelog.md
  src/components/AppMainView.tsx
  src/components/ControlPanel.tsx
  src/components/DeviceMemoryView.tsx
  src/components/ModemUpdateDialogView.tsx
  src/reducers/settingsReducer.ts
Labels: doc required, ui not required

#448 doc: remove MCUboot toggle
  doc/docs/overview.md
  doc/docs/screenshots/programmer_overview.png
Labels: documentation, doc required

#442 doc: add programming matrix table
  doc/docs/index.md
  doc/docs/programming_dk.md
  doc/docs/revision_history.md
Labels: documentation, doc required

#450 docs: MCU boot -> MCUboot
  src/components/ControlPanel.tsx
Labels: doc not required, ui not required

#451 docs: fix MCUboot spelling
  src/actions/targetActions.ts
  src/components/ControlPanel.tsx
Labels: doc not required, ui not required

#452 doc: rev history update
  doc/docs/revision_history.md
Labels: documentation, doc required

#449 Feat/dont close when programming
  Changelog.md
  package-lock.json
  package.json
  src/components/ControlPanel.tsx
  src/components/McuUpdateDialogView.tsx
  src/components/ModemUpdateDialogView.tsx
  src/components/UsbSdfuUpdateDialog.tsx
Labels: doc required, ui not required

#453 Dispatch calles
  src/components/ControlPanel.tsx
  src/components/McuUpdateDialogView.tsx
  src/components/ModemUpdateDialogView.tsx
Labels: doc not required, ui not required
