Repository NordicSemiconductor/pc-nrfconnect-programmer, pull requests merged in 2024-03, with the labels that each got.

#455 Feat: update shared
  package-lock.json
  package.json
Labels: doc not required, ui not required

#457 Feat: update shared
  package-lock.json
  package.json
Labels: doc not required, ui not required

#459 fix: remove file warning when no file is added
  Changelog.md
  src/components/FileMemoryBoxView.tsx
Labels: doc required, ui not required

#454 Release 4.3.0: update version
  Changelog.md
  package-lock.json
  package.json
Labels: doc not required, ui not required

#460 doc: revision history 4.3.0 update
  doc/docs/revision_history.md
Labels: documentation, doc required

#461 docs: update mentions of socs
  package.json
  src/components/ControlPanel.tsx
  src/components/DeviceMemoryView.tsx
Labels: doc required, ui not required
